name: CICD workflow for nonprd

run-name: Run workflow :${{ github.event.head_commit.message }}

on: 
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "feature/**"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO"
      - run: echo "feature"