name: CICD workflow for nonprd

run-name: Run workflow :${{ github.event.head_commit.message }}

on: 
  push:
      
jobs:
  init-workflow:
    name: Setup environments for workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo 1
  gen-init:
    needs:
      - init-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo 2

  test-code:
    needs:
      - init-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo 3

  build-push-image:
    needs: 
     - init-workflow
     - gen-init
     - test-code
    runs-on: ubuntu-latest
    steps:
      - run: echo 4

  deploy:
    needs:
    - init-workflow
    - gen-init
    - build-push-image
    runs-on: ubuntu-latest
    steps:
      - run: echo 5

  slack-noti:
    if: always()
    needs:
    - init-workflow
    - test-code
    - build-push-image
    - deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo 6