name: CICD workflow for nonprd

run-name: Run workflow :${{ github.event.head_commit.message }}

on: 
  push:
    branches:
      - "develop"
      - "release/**"
    tags:
      - '*'
  pull_request:
    branches:
      - "develop"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: echo "HELLO"
      - run: echo "${{ github.event.head_commit.message }}"