name: Genarate initial variables

on:
  workflow_call:
    inputs:
      label-runner:
        description: "label for select runner develop or production"
        type: string
        default: develop

    outputs:
      environment:
        description: "environment of project"
        value: ${{ jobs.init.outputs.environment }}
      image-tag-version:
        description: "environment of project"
        value: ${{ jobs.init.outputs.image-tag-version }}
jobs:
  init:
    name: Run genarate initial variables env,image-tag 
    runs-on: 
      - self-hosted
      - ${{ inputs.label-runner }}
      
    outputs:
      environment: ${{ steps.setvars.outputs.environment }}
      image-tag-version: ${{ steps.tag-image.outputs.image }}

    steps:
      - name: Genarate environment
        id: setvars
        run: |
          if [[ "${{github.ref_name}}" =~ ^develop.* ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

          if [[ "${{github.ref_name}}" =~ ^release.* ]]; then
            echo "environment=stg" >> $GITHUB_OUTPUT
          fi

          if [[ "${{github.ref_name}}" =~ ^main* ]]; then
            echo "environment=main" >> $GITHUB_OUTPUT
          fi

          if [[ "${{github.ref_name}}" =~ ^v.* ]]; then
            echo "environment=prd" >> $GITHUB_OUTPUT
          fi

      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 8

      - name: Genarate tag image
        id: tag-image
        env:
          IMAGE_TAG: ${{ steps.setvars.outputs.environment }}-${{ steps.short-sha.outputs.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
          ENVIROMMENT: ${{ steps.setvars.outputs.environment }}
        run: |
          if $ENVIROMMENT == 'prd'
          then
            echo "image=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT 
          fi