name: ci test

on:
  push:

jobs:
   build-and-deploy-nonprd:
    permissions:
      checks: write
      contents: read
      pull-requests: write
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - run: sudo npm install -g firebase-tools

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/206279441114/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-pool'
          # service_account: 'github-actions-sa@oceanft-stg.iam.gserviceaccount.com'
          # workload_identity_provider: 'projects/206279441114/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-actions-sa@oceanft-stg.iam.gserviceaccount.com'
          
      - name: Deploy
        run: |
          firebase use stg

  
